### ISSUE TITLE
Same DeamonSets scaled down more times

### ISSUE THREAD

**Issue by cristian98149** [caas-team/py-kube-downscaler#110]
## Issue
When scaling down DeamonSets, they are scaled down more times.

From POD's log, I see that a DeamonSet has been scaled down more than 600 times!

**Comment by samuel-esp** [comment]
Hi @cristian98149 could you attach some logs, in order to better understand the behavior? They don't need to be production logs, if you manage to replicate the behavior in a test cluster, it would be perfect as well

**Comment by cristian98149** [comment]
Sorry, I've probably catch the cause of this behavior.

Some DeamonSet is owned and controlled by operators that scale-up deamonset when py-kube-downscaler scale-up them.

This is the same thing that would happen with GitOps tools like ArgoCD. I know that on ArgoCD side a configuration can be made for ignoring replicas field changes. I don't know if the same can be done with operators.

Thank you.
