### ISSUE TITLE
Seeking info for using the new GHCR and mtr kube-downscaler Helm Chart.

### ISSUE THREAD

**Issue by larssb** [caas-team/py-kube-downscaler#18]
Thank you for working on #16 ... I'm currently trying to deploy the Helm Chart to a test cluster internally.

However, I can't seem to figure out the correct Helm Chart repo/registry URL.

I've tried:

- `oci://ghcr.io/caas-team/charts`
- `https://ghcr.io/caas-team/charts`
- as well as `oci://mtr.devops.telekom.de/caas/charts`

---

## Problem to solve

I get the following error when I try

### 404 Not found

```text
Error: looks like "https://ghcr.io/caas-team/charts" is not a valid chart repository or cannot be reached: failed to fetch https://ghcr.io/caas-team/charts/index.yaml : 404 Not Found
```

### Not a valid Chart repo

```text
Error: looks like "oci://ghcr.io/caas-team/charts" is not a valid chart repository or cannot be reached: object required
```

---

Thank you again for working on this ... I feel we're close here. Much appreciated.

**Comment by Fovty** [comment]
Hello @larssb,

Thank you for your feedback. I think it's simply a URL mismatch.

`helm pull oci://ghcr.io/caas-team/charts/kube-downscaler`
or specifying a certain version like:
`helm pull oci://ghcr.io/caas-team/charts/kube-downscaler --version 0.1.0`
worked for me.

The Helm chart will soon be updated and available at  `oci://ghcr.io/caas-team/charts/py-kube-downscaler` when PR  #15 gets merged. This update will align the chart to the new naming scheme.

Please let me know if this solves your issue.

**Comment by eumel8** [comment]
The assets of the software are on the right side of the repo page in Github linked. We missed to mention a section in the documentation, sorry for that, and as @Fovty mentioned, the app name will changed in the Chart.yaml

Meanwhile this should work:

```bash
$ helm fetch oci://ghcr.io/caas-team/charts/kube-downscaler     
Pulled: ghcr.io/caas-team/charts/kube-downscaler:0.1.0
Digest: sha256:3ddba71775c07c5d81a6123ff7b0c8cc8a8e08d1d398be989c10ad666a218dc
```

**Comment by larssb** [comment]
Maybe I should wait for the app name change. But, I might certainly tray later.So this: oci://ghcr.io/caas-team/charts/kube-downscaler is the repo url and kube-downscaler is the repo name?We have code that wraps helm to give a bunch of different things when managing helm charts … some of that code tries to helm repo add the repo and so on … why I’m asking for info.Thank you very much.--Mvh. / Kind regardsLars Bengtsson- Health is wealth, movement is medicine -On 16 Apr 2024, at 12.27, Frank Kloeker ***@***.***> wrote:﻿
The assets of the software are on the right side of the repo page in Github linked. We missed to mention a section in the documentation, sorry for that, and as @Fovty mentioned, the app name will changed in the Chart.yaml
Meanwhile this should work:
$ helm fetch oci://ghcr.io/caas-team/charts/kube-downscaler     
Pulled: ghcr.io/caas-team/charts/kube-downscaler:0.1.0
Digest: sha256:3ddba71775c07c5d81a6123ff7b0c8cc8a8e08d1d398be989c10ad666a218dc

**Comment by larssb** [comment]
Tried `helm repo add` directly and that's what's throwing an error. Namely:

```text
helm repo add caas oci://ghcr.io/caas-team/charts/kube-downscaler
Error: looks like "oci://ghcr.io/caas-team/charts/kube-downscaler" is not a valid chart repository or cannot be reached: object required
```

I hope it helps and thank you.

**Comment by Fovty** [comment]
This issue should be solved now. @larssb, please let me know if everything works for you as expected. py-kube-downscaler helm charts are available in our [Helm Charts repo](https://github.com/caas-team/helm-charts).

```
$ helm repo add caas-team https://caas-team.github.io/helm-charts/
"caas-team" has been added to your repositories
```

```
$ helm search repo caas-team
caas-team/py-kube-downscaler    0.1.1           24.4.0          A Helm chart for deploying py-kube-downscaler
caas-team/rancher-metrics       0.0.6           0.0.6           A Helm chart for Rancher Metrics
```

**Comment by larssb** [comment]
Hi @Fovty,

Just tried it and it works! Thank you very very much! With that info we have a winner 👍 🥇
