### ISSUE TITLE
Please release v0.2.0 of the Helm Chart to get #25 in.

### ISSUE THREAD

**Issue by larssb** [caas-team/py-kube-downscaler#29]
So #25 was merged into main. However, no new release of this chart was done. Could you please release this new version. Mostly because I can then get away from having to manually manipulate the `excluded namespaces` env. var. before applying e.g. `DEFAULT_DOWNTIME` in the `Kube down-scaler ConfigMap`.

Thank you very much.

**Comment by Fovty** [comment]
Release [v24.5.0](https://github.com/caas-team/py-kube-downscaler/releases/tag/v24.5.0) should solve this
