### ISSUE TITLE
Feature/helmchart: taking account about tolerations values into deployment template

### ISSUE THREAD

**Issue by remmercier** [caas-team/py-kube-downscaler#31]
It could be pretty awesome to handle tolerations in the next release of helm chart.

Currently, I forked the repo only to add this possibility cause I need it to handle correctly autoscaling with karpenter.

I tried to push feature branch with my (tiny) updates to make a pull request but I can't so here is what I done

```yaml
# at the end of template/deployment.yaml file
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

Thanks to continue supporting hjacobs's project cause I pretty sure it used in a lot of k8s clusters!

**Comment by JTaeuber** [comment]
Feature has been implemented.
