### ISSUE TITLE
Getting started with helm

### ISSUE THREAD

**Issue by GreyGlass1** [caas-team/py-kube-downscaler#34]
Hi, ive been redirected to this repository from the original on codeberg. I noticed you’ve removed the deploy folder in favour of helm charts, is that assumption correct?

I’m using the Charts readme but I’m getting errors whilst running the `helm install` command which looks out of date when reviewing the helm install manual, also shouldn’t there be a `helm repo add` command before doing the install? 

Thanks.

**Comment by LMantovan** [comment]
Hi, you can use 
`helm repo add https://caas-team.github.io/helm-charts/`

**Comment by JTaeuber** [comment]
Hi there,
we have indeed switched from regular deployments to a use with helm charts.
Generally there are 2 ways you can use the chart.

First one would be to directly reference the chart. To do that you clone the repo, change your current directory to the repo and run the following command:
```bash
helm install [deploy-name] ./chart
```

The other solution is to add the repo as @LMantovan mentioned and reference it like that.
First you need to run the command:
```bash
helm repo add [your-repo-name] https://caas-team.github.io/helm-charts/
```
and then you can run the helm install command:
```bash
helm install [deploy-name]  [your-repo-name]/py-kube-downscaler
```

I noticed that this is wrongly documented in the README at the moment.
I will fix this as soon as i have the time. Thank you for pointing this out.

**Comment by GreyGlass1** [comment]
Thanks, that’s worked for me.  Shall I leave this issue open until a PR has been raised & merged?

**Comment by JTaeuber** [comment]
Installation instructions should be fixed now.
