### ISSUE TITLE
Create Channel For The Project

### ISSUE THREAD

**Issue by samuel-esp** [caas-team/py-kube-downscaler#44]
## Issue / Proposal

Not an issue, but i think we should create like an official channel for the project in order to set a stable communication among contributors  (Slack/Discord)

**Comment by jonathan-mayer** [comment]
We created a slack workspace for the project: https://join.slack.com/t/py-kube-downscaler/shared_invite/zt-2o4uu6rcw-KjEOg7gy6mIS0KomevSDmA
