### ISSUE TITLE
Distributing Image on DockerHub And AWS ECR Public Gallery

### ISSUE THREAD

**Issue by samuel-esp** [caas-team/py-kube-downscaler#54]
### Proposal

We should think to distribute the official image through Docker Hub and AWS ECR Public Gallery in order to give the possibility to the user to choose their preferred registry

### Who can address the issue

Owners with write permission on the deployment pipeline

**Comment by eumel8** [comment]
Thanks for proposal. In my opinion Docker Hub is not the main source of container images anymore.  Due the changes in the business case of the service often you need paid account for usage due the rate limits. That's not the idea of Open Source. Images and Helm Charts for kube-downscaler are provided in 
- https://github.com/orgs/caas-team/packages?repo_name=py-kube-downscaler
- https://mtr.devops.telekom.de/repository/caas/py-kube-downscaler?tab=tags 
- https://mtr.devops.telekom.de/repository/caas/charts/py-kube-downscaler?tab=tags

So, two managed repos seems enough at this time

**Comment by samuel-esp** [comment]
Unfortunately you are right, I also encountered several problems with the rate limit. The release on the github is fine for everyone, ECR/Docker eventually would be a plus but what we have right now is good enough
