### ISSUE TITLE
The name of the ConfigMap for the kube-downscaler is not possible to control via the `configMapName` key in the Helm values.yaml file

### ISSUE THREAD

**Issue by larssb** [caas-team/py-kube-downscaler#55]
## Issue

The kube-downscaler helm chart provides the `configMapName` key. One gets the impression that, with this key, I can control what the name of the generated ConfigMap that Kube-downscaler uses for uptime, downtime configuration and so forth will be named.

But, the actual name of the `ConfigMap` will still be `py-kube-downscaler`. But, the `ConfigMap` ref in the `kube-downscaler` `Deployment` is referring to the name one uses on the `configMapName` key.

See this search on this GitHub repo: https://github.com/search?q=repo%3Acaas-team%2Fpy-kube-downscaler+configMapName&type=code

And then the actual `Helm template for the ConfigMap`: https://github.com/caas-team/py-kube-downscaler/blob/v24.5.2/chart/templates/configmap.yaml#L4

---

### Problem to solve

Make the a value configured on the `configMapName` key reflect through in all the places relevant to the `ConfigMap` that the `kube-downscaler` uses.

### Further details

I did upgrade to v24.5.2.

---

Thank you very much.

**Comment by Fovty** [comment]
Please give me feedback on whether the issue has been completely resolved.

**Comment by larssb** [comment]
Yes I sure will. Sorry. Been busy. I'll try to see to this ASAP.

**Comment by larssb** [comment]
Sorry for the delayed answer. I was finally able to get some time to test this. Yes I see what the code should work. However, because there was no new release of the Helm Chart itself, one does still get the release data/code from https://github.com/caas-team/py-kube-downscaler/commit/5508b19ff85c2f4089d8f3cbc7f043bf0c9f9099 also v0.2.1 of the kube-downscaler Helm Chart.

I did try to delete all my local Helm Cache. No luck.

So can we get a 0.2.2 please 🙏

**Comment by Fovty** [comment]
Sure, I will release a new version asap.
