### ISSUE TITLE
Feature Request: Add new annotation to allow overriding the downscaling grace period at the deployment level

### ISSUE THREAD

**Issue by michohl** [caas-team/py-kube-downscaler#72]
## Issue

I would like to be able to force a single deployment to have it's own grace period instead of using the command line options. 

### Problem to solve

I am creating an integration test for a deployment of py-kube-downscaler but when I create a deployment and set it to scale in a small window (to keep test time reasonable) I get the following log messages:

```
2024-07-19 18:09:30,688 DEBUG: https://192.168.0.1:443 "GET /api/v1/namespaces/addon-test HTTP/11" 200 None
2024-07-19 18:09:30,689 DEBUG: Deployment addon-test/test-downscaler-deployment has 3 replicas (original: None, uptime: ignored)
2024-07-19 18:09:30,689 INFO: Deployment addon-test/test-downscaler-deployment within grace period (900s), not scaling down (yet)
```

I would prefer my test to take < 5 minutes rather than 15+ minutes to run so I would like to be able to make it so this single test deployment scales down immediately regardless of the grace period.

### Proposal

First add a new annotation called `downscaler/grace-period` to this list:

https://github.com/caas-team/py-kube-downscaler/blob/9aa207856d695b6a0b3e56d382e597a32444eec5/kube_downscaler/scaler.py#L31-L41

Then update the `within_grace_period` function to check for this new annotation and prefer it over command line argument or ENV variable used to start the controller:

https://github.com/caas-team/py-kube-downscaler/blob/9aa207856d695b6a0b3e56d382e597a32444eec5/kube_downscaler/scaler.py#L83

**Comment by samuel-esp** [comment]
Hi @michohl,

Pull request is ready! #74

**Comment by michohl** [comment]
Wow, that's a quick turnaround time! Thanks for taking this on. Much appreciated :)

**Comment by samuel-esp** [comment]
you're welcome!

**Comment by samuel-esp** [comment]
The pull request was merged, issue can be closed
