### ISSUE TITLE
Feature request: custom annotations

### ISSUE THREAD

**Issue by ivanmartos** [caas-team/py-kube-downscaler#76]
## Issue
Motivation is for py-kube-downscaler to respect custom annotations

### Problem to solve

Currently annotations
```
ORIGINAL_REPLICAS_ANNOTATION = "downscaler/original-replicas"
FORCE_UPTIME_ANNOTATION = "downscaler/force-uptime"
FORCE_DOWNTIME_ANNOTATION = "downscaler/force-downtime"
UPSCALE_PERIOD_ANNOTATION = "downscaler/upscale-period"
DOWNSCALE_PERIOD_ANNOTATION = "downscaler/downscale-period"
EXCLUDE_ANNOTATION = "downscaler/exclude"
EXCLUDE_UNTIL_ANNOTATION = "downscaler/exclude-until"
UPTIME_ANNOTATION = "downscaler/uptime"
DOWNTIME_ANNOTATION = "downscaler/downtime"
DOWNTIME_REPLICAS_ANNOTATION = "downscaler/downtime-replicas"
GRACE_PERIOD_ANNOTATION="downscaler/grace-period"
```
Are respected. Idea is to be able to override these annotations.

### Proposal

Annotation names are currently hardcoded in https://github.com/caas-team/py-kube-downscaler/blob/main/kube_downscaler/scaler.py#L32

Proposal is to extend options and env variables that are respected in https://github.com/caas-team/py-kube-downscaler/blob/main/kube_downscaler/cmd.py to be able to override those annotations. In case no value is passed, current annotation will be respected

Since number of arguments of functions `autoscale_*` would grow significantly, maybe define a new object `AnnotationNames`  that would be created in https://github.com/caas-team/py-kube-downscaler/blob/main/kube_downscaler/main.py based on values from cmd.py and passed as an argument to `run_loop` and also to inner `autoscale_*` functions

**Comment by samuel-esp** [comment]
My fear about this feature is that it could create confusion for end-users (and for mantainers when looking into problems). Having standard annotations gives user a guidance on how to use the tool. We could implement this proposal in the future but I don't think this is high priority at the moment, I don't know what @JTaeuber and @jonathan-mayer think about it

**Comment by Fovty** [comment]
@samuel-esp we agree with you. Such a feature could certainly cause confusion, and the priority of this is currently not high enough

**Comment by ivanmartos** [comment]
Thank you for update @samuel-esp @Fovty 
In case I would implement such a feature and open a PR, do you think it could be merged?
Thank you
