### ISSUE TITLE
Question: Is there a way to use different schedules for different Namespace to turn up and down

### ISSUE THREAD

**Issue by suraj2410** [caas-team/py-kube-downscaler#93]
Hi,

I am just curious to know if there is a way to configure the following:
1) turn down a namespace A on weekends
2) turn down another namespace B on weekdays after say 6pm 

Is this possible with the current helm chart and how would the config look like?

**Comment by JTaeuber** [comment]
Hey there, sorry for the late response, I kind of didn't notice this issue until now.

Just to make sure: namespace B is not supposed to scale down on weekends?

If so there are multiple ways of achieving your desired result depending on the access you have to the kubernetes cluster.

Cluster wide
---
If you have cluster wide access and have/want the downscaler installed cluster wide, you don't really have to make any changes to the helm chart unless you want to rename or customize a few things according to your preferences.

The only thing you need to do is add the according annotation on your namespaces:
For namespace A: 
```yaml
downscaler/downtime: Sat-Sun 00:00-23:59 CET
```
and for namespace B: 
```yaml
downscaler/downtime: Mon-Fri 18:00-23:59 CET
```

Just remember to change the timezone to the one you need.

You can also write an `downscaler/uptime` annotation instead to define the time in which the downscaler is supposed to scale the workload up. Every other time the workloads are being scaled down. For example:
```yaml
downscaler/uptime: Mon-Fri 07:00-16:00 CET
```
scales down all workloads in a namespace between 4pm and 7am on the next day.

Limited access
---
If you only have limited access to the cluster and the downscaler isn't supposed to run cluster wide you need to change the following:
in values.yaml or a custom values.yaml file:
```yaml
constrainedDownscaler: true
constrainedNamespaces: [namespaceA,namespaceB]
```

and when installing the downscaler you should also specify the namespace it should be deployed in via `--namespace`.

Other than that the definition for the scaling works like the one in the cluster wide examples. You only need to set the annotation you need to the namespace.

A little more info on the installation process can be found [here](https://github.com/caas-team/py-kube-downscaler/blob/main/README.md#installation).

One last thing: Make sure to add workloads you want to scale down to the `--include-resources` in the values.yaml or your custom values.yaml.

Let me know if this solved your problem.

**Comment by JTaeuber** [comment]
Closing since there seems to be no response.
If you still have questions feel free to reopen or open a new issue.
